version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgress:latest
    restart: always
    env_file: .env.postgres
    # environment:
    #   - POSTGRES_DB: {{DB}}
    #   - POSTGRES_USER: {{USER}}
    #   - POSTGRES_PASSWORD: {{POSTGRES_PASSWORD}}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgres
